name: Simple Test
on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  DownloadInstallAndRunTE:
    name: Test
    timeout-minutes: 30
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Starting job [Event=${{ github.event_name }}]"
      - run: echo "This job is now running on a ${{ runner.os }} self-hosted server!"
      - run: |
          echo "PWD: $PWD"
      # - run: |
      #     $ProgressPreference = 'SilentlyContinue'
      #     Invoke-WebRequest -Uri "${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}" -OutFile ".\TE.exe" 
      # - run: echo "TestExecute downloaded - ${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}"
      # - run: dir
      #   shell: cmd
      # - run: .\TE.exe -SilentInstall
        shell: cmd
      - run: set PATH_TE="${{ vars.TEST_EXECUTE_BIN }}"
        shell: cmd
      - run: |
          $x = Start-Process -FilePath "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" -PassThru
          echo "pid=$($x.Id)" >> $ENV:GITHUB_OUTPUT
        shell: powershell
        id: edge
      - run: |
          Start-Sleep -s 15
        shell: powershell
      - run: |
          Stop-Process -Id ${{ steps.edge.outputs.pid }}
        shell: powershell
