name: TestExecute Simple Test
run-name: ${{ github.actor }} trying to run TestExecute
on: [push, workflow_dispatch]
jobs:
  DownloadInstallAndRunTE:
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Starting job [Event=${{ github.event_name }}]"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: |
          echo "PWD: $PWD"
      - run: Invoke-WebRequest -Uri "${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}" -OutFile ".\TE.exe" 
      - run: echo "TestExecute downloaded - ${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}"
      - run: dir
        shell: cmd
      - run: .\TE.exe -SilentInstall
        shell: cmd
      - run: set PATH_TE="${{ vars.TEST_EXECUTE_BIN }}"
        shell: cmd
      - name: Test RDP background
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          password: "${{ secrets.RDP_PW }}}" # You can also put the password in secrets as you wish.
          #foreground: false
      
      # - run: .\test-runner.bat ${{ secrets.TEST_EXECUTE_ACCESS_KEY }}
      #   shell: cmd
      # - run: echo "Test executed!"
      #   shell: cmd
