name: TestExecute Simple Test
on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  DownloadInstallAndRunTE:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ github.token }}"
      - run: echo "Starting job [Event=${{ github.event_name }}]"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: |
          echo "PWD: $PWD"
      - run: Invoke-WebRequest -Uri "${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}" -OutFile ".\TE.exe" 
      - run: echo "TestExecute downloaded - ${{ vars.TEST_EXECUTE_DOWNLOAD_URL }}"
      - run: dir
        shell: cmd
      - run: .\TE.exe -SilentInstall
        shell: cmd
      - run: set PATH_TE="${{ vars.TEST_EXECUTE_BIN }}"
        shell: cmd
      - name: Test RDP background
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          password: "${{ secrets.RDP_PW }}}" # You can also put the password in secrets as you wish.
          #foreground: false